#配置端口号
server:
  port: 8016

spring:
  application:
    name: footprintService  #配置服务名
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://47.52.88.176:3306/DB1_7?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = Asia/Shanghai
    username: user1_7
    password: ooad7
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 2
      #最大连接池数量
      max-active: 5
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名及密码
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: admin
        login-password: 123456
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1

  redis:
    host: 112.124.5.232
    jedis:
      pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#配置分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://112.124.5.232:8011/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.98.162.161
    non-secure-port: 8016

feign:
  hystrix:
    enabled: false
  client:
    config:
      share:
        connectTimeout: 120000
        readTimeout: 120000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true


#server:
#  port: 8091
#
#spring:
#  application:
#    name: footprintService
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://101.37.30.146:3306/oomall?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 606467
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  profiles:
#    active: dev
#  redis:
#    host: 101.37.30.146
#    port: 6379
#    #password: 123456
#    database: 0
#    jedis:
#      pool:
#        max-active: 50
#        max-wait: 3000
#        max-idle: 20
#        min-idle: 2
#    timeout: 5000
#
#eureka:
#  instance:
#    hostname: 101.37.30.146
#    metadata-map:
#      instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/ #Eureka Server地址
#
#ribbon:
#  eureka:
#    enabled: true
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#
#oomall:
#  redisexpiretime: 1
